page                       : "Página"
pagination_previous        : "Anterior"
pagination_next            : "Siguiente"
breadcrumb_home_label      : "Inicio"
breadcrumb_separator       : "/"
toc_label                  : "Contenidos"
ext_link_label             : "Enlace"
less_than                  : "menos de"
minute_read                : "minuto de lectura"
share_on_label             : "Compartir"
meta_label                 :
tags_label                 : "Etiquetas:"
categories_label           : "Categorías:"
date_label                 : "Actualizado:"
comments_label             : "Comentar"
comments_title             : "Deja un comentario"
more_label                 : "Ver más"
related_label              : "Quizás te interese"
follow_label               : "Seguir:"
feed_label                 : "Feed"
powered_by                 : "Creado por"
website_label              : "Sitio web"
email_label                : "Correo"
recent_posts               : "Entradas recientes"
undefined_wpm              : "Parámetro words_per_minute (palabras por minuto) no definido en _config.yml"
comment_form_info          : "No se publicará tu correo electrónico. Véanse marcados los campos obligatorios"
comment_form_comment_label : "Comentario"
comment_form_md_info       : "Markdown es compatible"
comment_form_name_label    : "Nombre"
comment_form_email_label   : "Correo electrónico"
comment_form_website_label : "Página web (opcional)"
comment_btn_submit         : "Enviar comentario"
comment_btn_submitted      : "Enviado"
comment_success_msg        : "¡Gracias por tu comentario! Aparecerá en la página cuando sea aprobado." 
comment_error_msg          : "Lo sentimos, ha habido un error con tu solicitud. Por favor, asegúrate de rellenar todos los campos obligatorios e inténtalo de nuevo."
loading_label              : "Cargando..."
lang_name: "Español"